### ISSUE TITLE
Service Account downloads lead to error 404

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-earthengine-driver#2]
Requests to the API that succeed with OAuth do not succeed with Service Account authentication.
Except the authentication itself via `ee.data.authenticateViaPrivateKey` all API calls are the same. The authentication itself seems to succeed, too, but further requests to the API, e.g. ImageCollection or downloading thumbnails fails with error 404:
```
Error: Server returned HTTP code: 404
    at Object.ee.data.handleResponse_ (c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:10633:9)
    at Object.ee.data.send_ (c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:10582:18)
    at Object.ee.data.getAlgorithms (c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:10257:24)
    at Function.ee.ApiFunction.initialize (c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:11922:78)
    at Function.ee.ApiFunction.importApi (c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:11930:18)
    at Function.ee.ImageCollection.initialize (c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:13185:54)
    at F.ee.ImageCollection [as constructor] (c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:13160:22)
    at new F (c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:11710:24)
    at Function.ee.ComputedObject.construct (c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:11713:10)
    at Object.ee.ImageCollection (c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:13152:30)
```

JS client versions: 0.1.136-prerelease up to 0.1.140-prerelease

**Comment by m-mohr** [comment]
I contacted Don from Google about the authentication issues and opened https://github.com/google/earthengine-api/issues/45.

**Comment by m-mohr** [comment]
The account wasn't in the authorization group anymore and therefore was not allowed to access the GEE APIs any longer.  If this happens again we were advised to contact Noel again.
